version: '3'

networks:
  bokanbefalinger:
    driver: bridge

volumes:
  virtuoso_data: {}
  redis_data: {}

services:
  bokanbefalinger_app:
    container_name: bokanbefalinger_app
    image: "TODO"
    networks:
      - bokanbefalinger

  bokanbefalinger_api:
    container_name: bokanbefalinger_api
    image: "TODO"
    networks:
      - bokanbefalinger

  redis:
    container_name: redis
    image: "redis:3.0.7-alpine"
    networks:
      - bokanbefalinger
    volumes:
      - "redis_data:/data"

  cron:
    container_name: cron
    image: "TODO"
    networks:
      - bokanbefalinger

  virtuoso_setup:
    container_name: virtuoso_setup
    image: alpine
    volumes:
      - ./config:/config
      - virtuoso_data:/data
    command:
      - "cp"
      - "/config/virtuoso.ini"
      - "/data/"

  virtuoso:
    container_name: virtuoso
    image: "digibib/virtuoso:29c4f313cdcc7d5cd1e331906b0d77b9363679ef"
    networks:
      - bokanbefalinger
    depends_on:
      - virtuoso_setup
    ports:
      - "8890:8890" # TODO remove when production
    volumes:
      - "virtuoso_data:/data"
