version: '3'

networks:
  bokanbefalinger:
    driver: bridge

volumes:
  virtuoso_data: {}
  redis_data: {}

services:
  app:
    container_name: app
    image: digibib/bokanbefalinger-app:e5135b71420db218d9d288a41f71596650fafc3d
    ports:
      - 8801:8801
    networks:
      - bokanbefalinger
    environment:
      GMAIL_ADR: sercet
      GMAIL_PASS: secret
      SECRET_SESSION_KEY: secret

  api:
    container_name: api
    image: digibib/bokanbefalinger-api:eda8240edc9943006c69041e54d4622c5536ce05
    networks:
      - bokanbefalinger
    environment:
      SECRET_SESSION_KEY: secret

  users:
    container_name: users
    image: digibib/bokanbefalinger-brukerstyring:d47b6472e2623d05eab80120fb1b461799b6099b
    networks:
      - bokanbefalinger
    environment:
      GMAIL_ADR: sercet
      GMAIL_PASS: secret
      SECRET_SESSION_KEY: secret

  redis:
    container_name: redis
    image: "redis:3.0.7-alpine"
    networks:
      - bokanbefalinger
    volumes:
      - "redis_data:/data"

  cron:
    container_name: cron
    build:
      context: cron
    networks:
      - bokanbefalinger

  virtuoso_setup:
    container_name: virtuoso_setup
    image: alpine
    volumes:
      - ./config:/config
      - virtuoso_data:/data
    command:
      - "cp"
      - "/config/virtuoso.ini"
      - "/data/"

  virtuoso:
    container_name: virtuoso
    image: "digibib/virtuoso:29c4f313cdcc7d5cd1e331906b0d77b9363679ef"
    networks:
      - bokanbefalinger
    depends_on:
      - virtuoso_setup
    volumes:
      - "virtuoso_data:/data"

  vindu:
    container_name: vindu
    image: digibib/virtuoso-vindu:bbfe3be70aaab563dafacb044770dcae187b14a0
    networks:
      - bokanbefalinger
    ports:
      - 7777:7777
